language: node_js
node_js:
  - '10'
  - '12'
before_install:
  - npm install -g grunt-cli
before_script:
  - grunt build
  - ./node_modules/.bin/babel dist -d dist
script: 
  - grunt jasmine --force
  - npm run test-ui
